# .graphclientrc.yml
sources:
  - name: unlockv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/unlock-protocol/{context.network:goerli-v2}
        retry: 2

documents:
  - ./src/subgraph/schema.graphql

additionalTypeDefs: |
  extend type Lock {
    network: String
  }

  extend type Query {
    allLocks(first: Int!, skip: Int!, networks: [String!]!): [Lock!]!
  }

additionalResolvers:
  - ../subgraph/resolvers.ts

codegen:
  contextType: 'MeshContext & { network: string }'
