name: Cache docker deps layers

on: workflow_call
jobs:
  cache_docker_deps_layer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="unlockprotocol/unlock-dev"
          echo "tagged_image=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT
          echo "latest=${IMAGE}:latest" >> $GITHUB_OUTPUT

      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKERHUB_USERNAME: op://secrets/docker-hub/username
          DOCKERHUB_TOKEN: op://secrets/docker-hub/credential

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BUILDKIT_INLINE_CACHE=1
          # Build only desired target
          target: deps
          push: true
          tags: ${{ steps.prep.outputs.tagged_image }},${{ steps.prep.outputs.latest }}
