name: Subgraphs deployment

on:
  workflow_call:
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: '1password service account token'
        required: true

jobs:
  coverage:
    name: Redeploy all existing subgraphs
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SUBGRAPH_DEPLOY_KEY: op://secrets/subgraph/hosted-service-deploy-key
      - run: yarn
      - run: yarn build
      - name: Deploying the subgraphs
        run: cd subgraph && yarn deploy-all
        shell: bash
