name: 'Staging / master branch'

on:
  push:
    branches:
      - master
      # - op-secrets # remove me but test once all secrets are in place!
jobs:
  run-all-tests:
    uses: ./.github/workflows/_tests.yml

  deploy-locksmith-staging:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith
      app-name: unlock-locksmith-staging

  deploy-locksmith-websub-staging:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith-websub
      build-dir: locksmith
      command: 'yarn websub:prod'
      container-type: worker
      app-name: locksmith-websub-staging

  # Netlify Deployments
  # The unlock-protocol-com site is built from `master` as we don't use a staging site for it.
  deploy-unlock-protocol-com-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }} # make sure we dont deploy from forks
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      bypass_diff_check: bypass
      service: unlock-protocol-com
      target-env: prod
      site-id: e52574b4-9da2-4000-a46d-3d4a3ed189a4
    secrets:
      NEXT_PUBLIC_UNLOCK_ENV: prod

  deploy-paywall-app:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: paywall-app
      target-env: staging
      bypass_diff_check: bypass
      site-id: f78363cb-8caa-4616-8fdc-f6ecc5df8c04

  deploy-wedlocks:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: wedlocks
      target-env: staging
      bypass_diff_check: bypass
      site-id: c5f7b41c-4f33-46f4-a28a-0de87c454425
    secrets:
      BASE64_WEDLOCKS_PRIVATE_KEY: ${{ secrets.WEDLOCKS_NETLIFY_STAGING_BASE64_WEDLOCKS_PRIVATE_KEY }}

  deploy-unlock-app:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: unlock-app
      target-env: staging
      bypass_diff_check: bypass
      site-id: d2e1173a-de41-475c-b46f-9e53653c4f77
    secrets:
      NEXT_PUBLIC_STRIPE_KEY: ${{ secrets.UNLOCK_APP_NETLIFY_STAGING_STRIPE_KEY }}

  cache_deps:
    uses: ./.github/workflows/_docker-cache.yml
    needs: run-all-tests
