name: 'Production Branch'

on:
  push:
    branches:
      - production

jobs:
  deploy-locksmith-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith
      app-name: unlock-locksmith-production
    secrets:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  deploy-locksmith-websub-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith-websub
      build-dir: locksmith
      command: 'yarn websub:prod'
      container-type: worker
      app-name: locksmith-websub-production
    secrets:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
