name: 'Production Branch'

on:
  push:
    branches:
      - production

jobs:
  run-all-tests:
    uses: ./.github/workflows/_tests.yml

  deploy-all-subgraphs:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_subgraph.yml

  deploy-locksmith-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith
      app-name: unlock-locksmith-production

  deploy-locksmith-websub-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith-websub
      build-dir: locksmith
      command: 'yarn websub:prod'
      container-type: worker
      app-name: locksmith-websub-production

  # Netlify Deployments
  deploy-paywall-app-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      bypass_diff_check: bypass
      service: paywall-app
      target-env: prod
      site-id: d7ab286a-d726-49c0-83b4-c89b52d97f5b

  deploy-wedlocks:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: wedlocks
      target-env: prod
      bypass_diff_check: bypass
      site-id: d527d16a-ec5c-4d4a-9a01-5ca649c1725b
    secrets:
      BASE64_WEDLOCKS_PRIVATE_KEY: ${{ secrets.WEDLOCKS_NETLIFY_PROD_BASE64_WEDLOCKS_PRIVATE_KEY }}

  deploy-unlock-app-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    needs: run-all-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      bypass_diff_check: bypass
      service: unlock-app
      target-env: prod
      site-id: 5426347d-0c26-4743-88bc-dc4168e47f91
    secrets:
      NEXT_PUBLIC_BASE64_WEDLOCKS_PUBLIC_KEY: ${{ secrets.UNLOCK_APP_NETLIFY_PROD_BASE64_WEDLOCKS_PUBLIC_KEY }}
      NEXT_PUBLIC_STRIPE_KEY: ${{ secrets.UNLOCK_APP_NETLIFY_PROD_STRIPE_KEY }}
      NEXT_PUBLIC_ETHPASS_KEY: ${{ secrets.UNLOCK_APP_NETLIFY_PROD_ETHPASS_KEY }}
      NEXT_PUBLIC_UNLOCK_ENV: prod
