name: Pull Request

on:
  pull_request:

jobs:
  # check which folder changed in the repo
  check-changes:
    uses: ./.github/workflows/_check.yml
    with:
      targets: '[
        "locksmith",
        "packages/contracts",
        "packages/hardhat-plugin",
        "packages/unlock-js",
        "packages/paywall",
        "smart-contracts",
        "subgraph",
        "unlock-protocol-com",
        "wedlocks",
        "unlock-app",
        "packages/core"
        ]'
      # run all tests if PR contains the 'run-all-tests' tag
      bypass: ${{ contains(github.event.pull_request.labels.*.name, 'run-all-tests')}}

  # run tests for folders that have changed
  run-tests:
    needs: check-changes
    # name: "Run the tests"
    if: ${{ needs.check-changes.outputs.changed != '[]' }}
    uses: ./.github/workflows/_tests.yml
    with:
      changed: ${{ needs.check-changes.outputs.changed }}

  smart-contracts-coverage:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changed != '[]' && contains(fromJson(needs.check-changes.outputs.changed), 'smart-contracts') }}
    uses: ./.github/workflows/_coverage.yml
    with:
      service: smart-contracts

  # Netlify Deployments (run as drafts, unpublished to main URL)
  deploy-unlock-protocol-com:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # make sure we dont deploy from forks
    needs: run-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: unlock-protocol-com
      target-env: staging
      site-id: 39b0a906-2c77-452b-9049-d04062303b1a

  deploy-paywall-app:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    needs: run-tests
    uses: ./.github/workflows/_netlify.yml
    with:
      service: paywall-app
      target-env: staging
      site-id: f78363cb-8caa-4616-8fdc-f6ecc5df8c04

  deploy-unlock-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    needs: run-tests
    steps:
      - name: 'Deploy Unlock App to netlify'
        uses: ./.github/workflows/_netlify.yml
        with:
          service: unlock-app
          target-env: staging
          site-id: d2e1173a-de41-475c-b46f-9e53653c4f77
